name: AI Code Reviewer

on:
  # push:
  #   branches:
  #     - main
  #     - '**' # (옵션) 모든 브랜치 포함
  pull_request:
    types:
      - opened
      - synchronize
      - edited # (옵션: PR 편집 시에도 리뷰)
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: Ostrich-Cyber-Risk/ai-codereviewer@main
        with:
          OCTOKIT_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
